management_app/approval/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^approval$',                                            views.ApprovalListView.as_view(),        name = 'approval_list'),
	url(r'^approval/(?P<pk>[0-9]+)/details$',                     views.details,                           name = 'approval_details'),
	url(r'^approval/(?P<pk>[0-9]+)/approve$',                     views.approve,                           name = 'approval_approve'),
	url(r'^approval/(?P<pk>[0-9]+)/approve_and_forced_start$',    views.approve_and_forced_start,          name = 'approval_approve_and_forced_start'),
	url(r'^approval/(?P<pk>[0-9]+)/(?P<reason>.+)/reject$',       views.reject,                            name = 'approval_reject'),
]

management_app/management_app/urls.py
from django.conf.urls import url
from django.urls import include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from common.views import index


urlpatterns = [
    url(r'^',      include('admin_event_source.urls')),
    url(r'^',      include('admin_event_source_type.urls')),
    url(r'^',      include('admin_errordetector.urls')),
    url(r'^',      include('admin_execution_flow.urls')),
    url(r'^',      include('monitoring.urls')),
    url(r'^',      include('scheduler.urls')),
    url(r'^',      include('executor.urls')),
    url(r'^',      include('approval.urls')),
    url(r'^',      include('statistics.urls')),
    url(r'^',      include('worker_status.urls')),
    url(r'^',      include('dashboard.urls')),

    url(r'^help$',  TemplateView.as_view(template_name='help.html'), name='helpp'),

    url(r'^admin/',         admin.site.urls),

    url(r'^api-auth/',      include('rest_framework.urls', namespace='rest_framework')),
    
    url(r'^$', index, name='main'),

    url(r'^loggedout$', TemplateView.as_view(template_name='loggedout.html')),

]
if settings.REACTION_AUTH_TYPE == 'SAML':
    urlpatterns.append(url(r'^$', index, name='login'))
    urlpatterns.insert(0, url(r'^saml2/', include('djangosaml2.urls')))
else:
    urlpatterns.append(url(r'^accounts/', include('django.contrib.auth.urls')))

# for custom error handling
handler500 = 'common.view_utils.custom_500'
handler404 = 'common.view_utils.custom_404'
handler403 = 'common.view_utils.custom_403'

# if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns = [
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    ] + urlpatterns

management_app/scheduler/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^scheduler$',                                   views.SchedulerList.as_view(),          name='scheduler_list'),

    url(r'^scheduler/(?P<pk>[0-9]+)/update$',             views.SchedulerUpdate.as_view(),        name='scheduler_update'),

    url(r'^scheduler/create$',                            views.SchedulerCreate.as_view(),        name='scheduler_create'),

    url(r'^scheduler/(?P<pk>[0-9]+)/delete$',             views.delete_scheduler,                 name='scheduler_delete'),
    
    url(r'^scheduler/(?P<pk>[0-9]+)/start$',              views.start_scheduling,                 name='scheduler_start'),
    url(r'^scheduler/(?P<pk>[0-9]+)/stop$',               views.stop_scheduling,                  name='scheduler_stop'),
    
    # for REST service
    url(r'^scheduler/getNextRun$',                        views.get_next_run,                     name='scheduler_get_next_run'),
]

management_app/scheduler/models.py
from django.db import models
from admin_event_source.models import ParentModel
from admin_execution_flow.models import ExecutionFlow

# ################################## ScheduledExecutionFlow ##################################
class ScheduledExecutionFlow(ParentModel):
    name = models.CharField(max_length=200, unique=True)
    reason = models.TextField(blank = True, null = True)
    cron_expression = models.CharField(max_length=150)
    execution_flow = models.ForeignKey(ExecutionFlow, on_delete=models.CASCADE)
    scheduled_already = models.BooleanField(default=False)
    error_at_last_run = models.TextField(blank = True, null = True)

    class Meta:
        db_table = 'SCHEDULED_EXECUTION_FLOW'
        default_permissions = ()


    def __str__(self):
        return "Name: {}\nReason: {}\nCron expression: {}".format(self.name, self.reason, self.cron_expression)

management_app/scheduler/forms.py
from django import forms
from .models import ScheduledExecutionFlow

class SchedulerForm(forms.ModelForm):
    reason = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = ScheduledExecutionFlow
        fields = ['name', 'reason', 'cron_expression', 'execution_flow']

    def __init__(self, *args, **kwargs):
        super(SchedulerForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['reason'].widget.attrs['class'] = 'form-control'
        self.fields['reason'].widget.attrs['style'] = 'resize: vertical;'
        self.fields['cron_expression'].widget.attrs['class'] = 'form-control'
        self.fields['execution_flow'].widget.attrs['class'] = 'form-control'

management_app/scheduler/views.py
import logging
from django.views.generic import UpdateView, CreateView
from common.view_utils import FilteredListView
from .models import ScheduledExecutionFlow
from admin_execution_flow.models import ExecutionFlow
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import SchedulerForm
from cron_descriptor import ExpressionDescriptor, CasingTypeEnum, Exception
from scheduler.service_clients import *
from django.shortcuts import redirect
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from common.utils import *
from django.shortcuts import get_object_or_404, render
from common.rest_utils import login_required_for_rest
from django.db.utils import IntegrityError


logger = logging.getLogger('root')


class SchedulerList(LoginRequiredMixin, PermissionRequiredMixin, FilteredListView):
    paginate_by = 10
    template_name = 'scheduler/list.html'
    permission_required = 'auth.can_use_scheduler'

    def get_queryset(self):
        # build the filter
        filter = self.build_filter()
        # build the order
        order = ['name' if 'order' not in self.request.GET else self.request.GET.get('order'), 'id']
        # build the access_groups filter
        access_groups_conditions = build_filter_access_groups(self.request.user.profile.access_groups, False, 'execution_flow__')
        logger.info('get_queryset - {}|  filter :{},    order: {}'.format(__name__, filter, order))
        return ScheduledExecutionFlow.objects.filter(access_groups_conditions, **filter).order_by(*order)

    def get_context_data(self, **kwargs):
        context = super(SchedulerList, self).get_context_data(**kwargs)
        # if error occurred during the REST call then a modal dialog has to be displayed with message
        if self.request.session.has_key('successful'):
            context['successful'] = self.request.session['successful']
            del self.request.session['successful']
            context['errorMessage'] = self.request.session['errorMessage']
            del self.request.session['errorMessage']
        return context


class SchedulerUpdateCreateView(LoginRequiredMixin, PermissionRequiredMixin):
    model = ScheduledExecutionFlow
    form_class = SchedulerForm
    template_name = 'scheduler/form.html'
    permission_required = 'auth.can_use_scheduler'

    def get_success_url(self):
        return reverse_lazy('scheduler_list')

    def get_context_data(self, **kwargs):
        # setting the parent combo box
        context = super(SchedulerUpdateCreateView, self).get_context_data(**kwargs)
        # build the access_groups filter
        access_groups_conditions = build_filter_access_groups(self.request.user.profile.access_groups, False, '')
        # setting the execution flow id and name to the dropdown
        choices = []
        for ef in ExecutionFlow.objects.filter(access_groups_conditions, ~Q(status='INVALID')).order_by('name'):
            choices.append((ef.id, ef.name))
            context['form'].fields['execution_flow'].choices = choices
        context['form_operation'] = 'update' if self.__class__.__name__ == 'SchedulerUpdate' else 'create'
        # setting the description of the cron expression
        if context['form_operation'] == 'update':
            descripter = ExpressionDescriptor(context['scheduledexecutionflow'].cron_expression,
                                              throw_exception_on_parse_error = True,
                                              casing_type = CasingTypeEnum.Sentence,
                                              use_24hour_time_format = True)
            try:
                context['cron_expression_description'] = descripter.get_description()
            except Exception.FormatException as e:
                context['cron_expression_description'] = 'The cron expression is not valid! The error is "{}"'.format(e)
        else:
            context['cron_expression_description'] = 'Please save it first!'
        return context


class SchedulerUpdate(SchedulerUpdateCreateView, UpdateView):
    pass


class SchedulerCreate(SchedulerUpdateCreateView, CreateView):
    pass


@login_required
@permission_required('auth.can_use_scheduler', raise_exception=True)
def delete_scheduler(request, pk):
    logger.info('delete_scheduler is called - request={}; pk={}'.format(request,pk))
    try:
        ScheduledExecutionFlow.objects.filter(id = pk).delete()
        return HttpResponseRedirect(reverse_lazy('scheduler_list'))
    except IntegrityError:
        message = 'The scheduled execution flow be deleted as it is currently being used in somewhere else!'
        logger.exception(message)
        return render(request, 'business_error.html', {'message': message})


@login_required
@permission_required('auth.can_use_scheduler', raise_exception=True)
def start_scheduling(request, pk):
    logger.info('start_scheduling is called - request={}; pk={}'.format(request, pk))
    # call the REST of reaction engine
    rest_response = call_start_scheduling(pk)
    if rest_response.successful:
        return redirect('scheduler_list')
    else:
        request.session['successful'] = 'N'
        request.session['errorMessage'] = str(rest_response.error_code) + ' - ' + rest_response.message
        return redirect('scheduler_list')


@login_required
@permission_required('auth.can_use_scheduler', raise_exception=True)
def stop_scheduling(request, pk):
    logger.info('stop_scheduling is called - request={}; pk={}'.format(request, pk))
    scheduled_execution_flow = get_object_or_404(ScheduledExecutionFlow, pk=pk)
    scheduled_execution_flow.scheduled_already = False
    scheduled_execution_flow.save()
    return redirect('scheduler_list')


@login_required_for_rest
@permission_required('auth.can_use_scheduler', raise_exception=True)
@api_view(['POST'])
def get_next_run(request):
    logger.info('Getting the next run date of a cron expression - request.data={}'.format(request.data))
    # call the REST of reaction engine
    try:
        rest_response = call_get_next_run(request.data.get('cron'))
        if rest_response.successful:
            return Response(rest_response.message, status=status.HTTP_200_OK)
        else:
            return Response(rest_response.message, status=rest_response.error_code)
    except Exception as e:
        return Response('The Reaction Engine cannot be called! ' + str(e), status=500)

management_app/scheduler/templates/scheduler/form.html
{% extends "base.html" %}

{% block title %} {% if form_operation == "update" %}Edit an existing scheduled execution flow{% else %}Create a new scheduled execution flow{% endif %} {% endblock %}

{% block content %}

    {% load static %}
    {% load custom_tags %}

    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'switch.css' %}" />

    <script src="{% static 'jquery-ui-1.12.1/jquery-ui.js' %}"></script>
	<script src="{% static 'mermaid/mermaid.min.js' %}"></script>


    <script>
        $(document).ready(function () {
            $( '#icon_question_cron_expression' ).tooltip({
                content: $('#t_cron_expression').html(),
                open: function (event, ui) {
                    ui.tooltip.css("max-width", "900px");
                }
            });

            refreshNextRun();
        });

        $("#id_cron_expression").blur(function() {
            refreshNextRun();
        });

        function refreshNextRun() {
            var cron = $("#id_cron_expression").val();
            if (cron){
                // getting the CSRF token (see https://docs.djangoproject.com/en/1.11/ref/csrf/)
                var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

                $.ajax({
                    type: 'POST',
                    url: '{% url "scheduler_get_next_run" %}',
                    data: {'cron':cron},
                    timeout: 20000,
                    accepts: {
                        text: "application/json"
                    },
                    success: function (_date, text) {
                        $("#l_next_run").text(_date);
                    },
                    error: function (request, status, error) {
                        $("#l_next_run").text("Warning! The server cannot be called! " + request.status + "(" + request.statusText + ")  " + request.responseText);
                    }
                });
            }
        }

    </script>

    <div class="heading1">Scheduler administration - {% if form_operation == "update" %}Edit{% else %}Create{% endif %}</div>

    <div class="container" style="padding-top: 30px;">
        <form method="post">
            {% csrf_token %}
			{{ form.non_field_errors }}

            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Name :</label> <span class="glyphicon glyphicon-asterisk"></span>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{ form.cron_expression.id_for_label }}">Cron expression:</label> <span class="glyphicon glyphicon-asterisk"></span> <span id="icon_question_cron_expression" class="glyphicon glyphicon-question-sign" title=""></span>
                        {{ form.cron_expression }}
                        {{ form.cron_expression.errors }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{ form.execution_flow.id_for_label }}">Execution flow:</label> <span class="glyphicon glyphicon-asterisk"></span>
                        {{ form.execution_flow }}
                        {{ form.execution_flow.errors }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label >The description of the interpreted cron expression:</label>
                {{ cron_expression_description }}
            </div>
            <div class="form-group">
                <label>The next possible run of the flow:</label>
                <label id="l_next_run" style="font-weight: normal; font-style: italic;"></label>
            </div>
            <div class="form-group">
                <label for="{{ form.reason.id_for_label }}">Reason:</label>
                {{ form.reason }}
                {{ form.reason.errors }}
            </div>

            <input type="submit" value="Save" class="btn btn-primary"/>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Cancel</a>
        </form>

    </div>

<!-- TOOLTIP for cron expression -->
<div id="t_cron_expression"  style="width: 990px;display:none">
<pre><b>* * * * * *</b>
| | | | | |
| | | | | +-- Day of week       (range: 0-7 (0 or 7 is Sun, or use names))
| | | | +---- Month             (range: 1-12 (or names))
| | | +------ Day of month      (range: 1-31)
| | +-------- Hour              (range: 0-23)
| +---------- Minute            (range: 0-59)
+------------ Second            (range: 0-59)</pre>
<p>A field may be an asterisk (*), which always stands for <i>first-last</i>.</p>
<p>Ranges of numbers are allowed.  Ranges are two numbers separated with a
hyphen.  The specified range is inclusive.  For example, 8-11 for an
<i>hours</i> entry specifies execution at hours 8, 9, 10 and 11.</p>
<p>Lists are allowed.  A list is a set of numbers (or ranges) separated by
commas.  Examples: <i>1,2,5,9</i>, <i>0-4,8-12</i>.</p>
<p>Step values can be used in conjunction with ranges.  Following a range
with `<i>number</i> specifies skips of the number's value through the
range.  For example, <i>0-23/2</i> can be used in the hours field to specify
command execution every other hour (the alternative in the V7 standard is
<i>0,2,4,6,8,10,12,14,16,18,20,22</i>).  Steps are also permitted after an
asterisk, so if you want to say <i>every two hours</i>, just use <i>*/2</i>.</p>

</div>
{% endblock %}

management_app/scheduler/templates/scheduler/list.html
{% extends "base.html" %}

{% block title %}Scheduler administration{% endblock %}

{% block content %}

    {% load static %}
    {% load custom_tags %}

    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1/jquery-ui.css' %}" />

    <script src="{% static 'jquery-ui-1.12.1/jquery-ui.js' %}"></script>

    <script>
        $(document).ready(function () {
            // displaying an error dialog if error occurred during the REST call
            {% if successful %}
                $("#l_error_message").html('{{errorMessage}}');
                $("#d_error").removeClass("hide");
                $("#d_error").dialog( "open" )
            {% endif %}
        });
    </script>

    <!-------------------------------------- MAIN CONTENT -------------------------------------------->
    <div class="heading1">Scheduler administration</div>

    <div class="container">
        <table class="data_table table-hover">
            <tr>
                <th class="data_table_header">
                    <a href="?{% url_replace order='name' filter_name=filter_name filter_reason=filter_reason filter_cron_expression=filter_cron_expression filter_execution_flow__name=filter_execution_flow__name filter_scheduled_already=filter_scheduled_already %}">Name</a>
                    {% autoescape off %}{% table_header_sort_icon 'name' %}{% endautoescape %}
                </th>
                <th class="data_table_header">
                    <a href="?{% url_replace order='reason' filter_name=filter_name filter_reason=filter_reason filter_cron_expression=filter_cron_expression filter_execution_flow__name=filter_execution_flow__name filter_scheduled_already=filter_scheduled_already %}">Reason</a>
                    {% autoescape off %}{% table_header_sort_icon 'reason' %}{% endautoescape %}
                </th>
                <th class="data_table_header">
                    <a href="?{% url_replace order='cron_expression' filter_name=filter_name filter_reason=filter_reason filter_cron_expression=filter_cron_expression filter_execution_flow__name=filter_execution_flow__name filter_scheduled_already=filter_scheduled_already %}">Cron expression</a>
                    {% autoescape off %}{% table_header_sort_icon 'cron_expression' %}{% endautoescape %}
                </th>
                <th class="data_table_header">
                    <a href="?{% url_replace order='execution_flow__name' filter_name=filter_name filter_reason=filter_reason filter_cron_expression=filter_cron_expression filter_execution_flow__name=filter_execution_flow__name filter_scheduled_already=filter_scheduled_already %}">Execution flow</a>
                    {% autoescape off %}{% table_header_sort_icon 'execution_flow__name' %}{% endautoescape %}
                </th>
                <th class="data_table_header">
                    <a href="?{% url_replace order='scheduled_already' filter_name=filter_name filter_reason=filter_reason filter_cron_expression=filter_cron_expression filter_execution_flow__name=filter_execution_flow__name filter_scheduled_already=filter_scheduled_already %}">Already scheduled?</a>
                    {% autoescape off %}{% table_header_sort_icon 'scheduled_already' %}{% endautoescape %}
                </th>
                <th class="data_table_header">Error at last run</th>

                <th colspan="3"/>
            </tr>
            <tr>
                <form method="get" action="{% url 'scheduler_list' %}">

                <td>
                    <input type="text" value="{{filter_name}}" name="filter_name" style="width: 100%;"/>
                </td>
                <td>
                    <input type="text" value="{{filter_reason}}" name="filter_reason" style="width: 100%;"/>
                </td>
                <td>
                    <input type="text" value="{{filter_cron_expression}}" name="filter_cron_expression" style="width: 100%;"/>
                </td>
                <td>
                    <input type="text" value="{{filter_execution_flow__name}}" name="filter_execution_flow__name" style="width: 100%;"/>
                </td>
                <td>
                    <input type="text" value="{{filter_scheduled_already}}" name="filter_scheduled_already" style="width: 100%;"/>
                </td>
                <td/>
                <td colspan="3" style="width: 110px;">
                    <input type="submit" name="submit" value="Filter!" class="btn btn-info"/>
                </td>
                </form>
            </tr>
        {% for scheduled_execution_flow in object_list %}
            <tr class="{% cycle 'data_table_event_odd' 'data_table_even_line' %}">
                <td>{{ scheduled_execution_flow.name }}</td>
                <td title="{{scheduled_execution_flow.reason}}">{{ scheduled_execution_flow.reason|truncatechars:40 }}</td>
                <td>{{ scheduled_execution_flow.cron_expression }}</td>
                <td title="{{scheduled_execution_flow.execution_flow}}">{{ scheduled_execution_flow.execution_flow.name|truncatechars:40 }}</td>
                <td {% if scheduled_execution_flow.scheduled_already %}style="color:green"{% else %}style="color:red"{% endif %}>{{ scheduled_execution_flow.scheduled_already }}</td>
                <td title="{{ scheduled_execution_flow.error_at_last_run|default_if_none:""|truncatechars:600 }}">{{ scheduled_execution_flow.error_at_last_run|default_if_none:""|truncatechars:30 }}</td>
                <td style="width: 60px;">
                    <a href="{% url 'scheduler_update' pk=scheduled_execution_flow.id %}">Edit</a>
                </td>
                <td style="width: 60px;">
                    <a href="{% url 'scheduler_delete' pk=scheduled_execution_flow.id %}" onclick="return confirm('Are you sure to delete the scheduled execution flow?')">Delete</a>
                </td>
                <td>
                    {% if scheduled_execution_flow.scheduled_already == False %}
                        <a href="{% url 'scheduler_start' pk=scheduled_execution_flow.id %}" onclick="return confirm('Are you sure to start to schedule of the execution flow?')" title="Schedule it!"> <span class="glyphicon glyphicon-time"></span> </a>
                    {% else %}
                        <a href="{% url 'scheduler_stop' pk=scheduled_execution_flow.id %}" onclick="return confirm('Are you sure to deschedule the scheduled execution flow?')" title="Deschedule it!"> <span class="glyphicon glyphicon-minus-sign"></span> </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
            <tr>
                {# .... **Now the pagination section** .... #}
                <td colspan="9">
                {% if is_paginated %}
                    <span class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="?{% url_replace page=page_obj.previous_page_number %}" class="btn btn-info">&#60;&#60; Previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?{% url_replace page=page_obj.next_page_number %}" class="btn btn-info">Next &#62;&#62;</a>
                            {% endif %}
                        </span>
                    </span>
                {% endif %}
                </td>
            </tr>
            {# .... **the Create,... buttons** .... #}
            <tr>
                <td colspan="9">
                    <a href="{% url 'scheduler_create'%}" class="btn btn-primary">Create</a>
                </td>
            </tr>
        </table>

    </div>

{% endblock %}