management_app/admin_errordetector/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^administration/errordetector$',                                         views.ErrorDetectorList.as_view(),                  name='admin_errordetector_list'),
    url(r'^administration/errordetector/(?P<pk>[0-9]+)/update$',                   views.ErrorDetectorUpdate.as_view(),                name='admin_errordetector_update'),
    url(r'^administration/errordetector/create$',                                  views.ErrorDetectorCreate.as_view(),                name='admin_errordetector_create'),
    url(r'^administration/errordetector/(?P<pk>[0-9]+)/delete$',                   views.delete_errordetector,                         name='admin_errordetector_delete'),
    url(r'^administration/errordetector/(?P<pk>[0-9]*)/remove_history',            views.remove_history,                               name='admin_errordetector_remove_history'),

    # for REST service
    url(r'^administration/errordetector/event_source/(?P<pk>[0-9]+)$',             views.get_event_source,                             name='admin_errordetector_event_source'),
    url(r'^administration/errordetector/endpoint/(?P<pk>[0-9]+)$',                 views.get_errordetector_endpoint,                   name='admin_errordetector_get_endpoint')

]

management_app/approval/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^approval$',                                            views.ApprovalListView.as_view(),        name = 'approval_list'),
	url(r'^approval/(?P<pk>[0-9]+)/details$',                     views.details,                           name = 'approval_details'),
	url(r'^approval/(?P<pk>[0-9]+)/approve$',                     views.approve,                           name = 'approval_approve'),
	url(r'^approval/(?P<pk>[0-9]+)/approve_and_forced_start$',    views.approve_and_forced_start,          name = 'approval_approve_and_forced_start'),
	url(r'^approval/(?P<pk>[0-9]+)/(?P<reason>.+)/reject$',       views.reject,                            name = 'approval_reject'),
]

management_app/management_app/urls.py
from django.conf.urls import url
from django.urls import include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from common.views import index


urlpatterns = [
    url(r'^',      include('admin_event_source.urls')),
    url(r'^',      include('admin_event_source_type.urls')),
    url(r'^',      include('admin_errordetector.urls')),
    url(r'^',      include('admin_execution_flow.urls')),
    url(r'^',      include('monitoring.urls')),
    url(r'^',      include('scheduler.urls')),
    url(r'^',      include('executor.urls')),
    url(r'^',      include('approval.urls')),
    url(r'^',      include('statistics.urls')),
    url(r'^',      include('worker_status.urls')),
    url(r'^',      include('dashboard.urls')),

    url(r'^help$',  TemplateView.as_view(template_name='help.html'), name='helpp'),

    url(r'^admin/',         admin.site.urls),

    url(r'^api-auth/',      include('rest_framework.urls', namespace='rest_framework')),
    
    url(r'^$', index, name='main'),

    url(r'^loggedout$', TemplateView.as_view(template_name='loggedout.html')),

]
if settings.REACTION_AUTH_TYPE == 'SAML':
    urlpatterns.append(url(r'^$', index, name='login'))
    urlpatterns.insert(0, url(r'^saml2/', include('djangosaml2.urls')))
else:
    urlpatterns.append(url(r'^accounts/', include('django.contrib.auth.urls')))

# for custom error handling
handler500 = 'common.view_utils.custom_500'
handler404 = 'common.view_utils.custom_404'
handler403 = 'common.view_utils.custom_403'

# if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns = [
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    ] + urlpatterns

management_app/admin_errordetector/models.py
from django.db import models
from admin_event_source.models import ParentModel, EventSource

# ################################## ErrorDetector ##################################
class ErrorDetector(ParentModel):
    name = models.CharField(max_length=200, blank=False, unique=True)
    message_pattern = models.CharField(max_length=400, blank=True, null=True)
    activated = models.BooleanField(default=False)
    confirmation_needed = models.BooleanField(default=False)
    multiple_events_cnt = models.IntegerField(blank=True, null=True)
    multiple_events_timefr = models.IntegerField(blank=True, null=True)
    execution_flow = models.ForeignKey("admin_execution_flow.ExecutionFlow", on_delete=models.DO_NOTHING)
    event_source = models.ForeignKey(EventSource, on_delete=models.DO_NOTHING)
    identifiers = models.CharField(max_length=3000, blank=True, null=True)

    class Meta:
        db_table = 'ERROR_DETECTOR'
        default_permissions = ()

    def __str__(self):
        return "Name: {}\nMessage pattern: {}\nConfirmation needed: {}\nActivated: {}".format(self.name,
                                                                                              self.message_pattern,
                                                                                              self.confirmation_needed,
                                                                                              self.activated)

management_app/admin_errordetector/forms.py
from django import forms

from .models import ErrorDetector
from admin_event_source.models import EventSource

class ErrorDetectorForm(forms.ModelForm):

	class Meta:
		model = ErrorDetector
		fields = ['name', 'activated', 'confirmation_needed', 'multiple_events_cnt', 'multiple_events_timefr', 'execution_flow',
				  'event_source', 'identifiers', 'message_pattern']

	def __init__(self, *args, **kwargs):
		super(ErrorDetectorForm, self).__init__(*args, **kwargs)
		self.fields['name'].widget.attrs['class'] = 'form-control'
		self.fields['activated'].widget.attrs['class'] = 'form-control'
		self.fields['activated'].widget.attrs['style'] = 'width: 50px;'
		self.fields['confirmation_needed'].widget.attrs['class'] = 'form-control'
		self.fields['confirmation_needed'].widget.attrs['style'] = 'width: 50px;'
		self.fields['multiple_events_cnt'].widget.attrs['class'] = 'form-control'
		self.fields['multiple_events_cnt'].widget.attrs['style'] = 'width: 150px;'
		self.fields['multiple_events_timefr'].widget.attrs['class'] = 'form-control'
		self.fields['multiple_events_timefr'].widget.attrs['style'] = 'width: 150px;'
		self.fields['execution_flow'].widget.attrs['class'] = 'form-control'
		self.fields['event_source'].widget.attrs['class'] = 'form-control'
		self.fields['event_source'].widget.attrs['onchange'] = 'rebuildIdentifiers()'
		self.fields['message_pattern'].widget.attrs['class'] = 'form-control'


	def clean(self):
		cleaned_data = super(ErrorDetectorForm, self).clean()
		cnt = cleaned_data.get('multiple_events_cnt')
		if cnt and int(cnt) < 2:
			self.add_error('multiple_events_cnt', 'If the multiple event counter is set then it has to be bigger than 1!')
		if not cnt:
			cleaned_data['multiple_events_timefr'] = None

management_app/admin_errordetector/views.py
from django.views.generic import UpdateView, CreateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .models import ErrorDetector
from admin_event_source.models import EventSource
from admin_execution_flow.models import ExecutionFlow
from .forms import ErrorDetectorForm
from monitoring.models import Event
from common.view_utils import FilteredListView
import logging
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from admin_event_source.views import *
from common.utils import *
from django.db.utils import IntegrityError
import urllib


# Create your views here.
logger = logging.getLogger('root')


class ErrorDetectorList(LoginRequiredMixin, PermissionRequiredMixin, FilteredListView):
    # Get an instance of a logger
    paginate_by = 10
    template_name = 'admin_errordetector/list.html'
    permission_required = 'auth.can_use_admin_errordetector'

    def get_queryset(self):
        filter = self.build_filter()
        order = ['name' if 'order' not in self.request.GET else self.request.GET.get('order') , 'id']
        logger.info('get_queryset - {}|  filter :{},    order: {}'.format(__name__, filter, order))
        return ErrorDetector.objects.filter(**filter).order_by(*order)


class ErrorDetectorUpdateCreateView(LoginRequiredMixin, PermissionRequiredMixin):
    model = ErrorDetector
    form_class = ErrorDetectorForm
    template_name = 'admin_errordetector/form.html'
    permission_required = 'auth.can_use_admin_errordetector'

    def get_success_url(self):
        return reverse_lazy('admin_errordetector_list')

    def get_context_data(self, **kwargs):
        # setting the parent combo box
        context = super(ErrorDetectorUpdateCreateView, self).get_context_data(**kwargs)
        # setting the execution flow id and name to the dropdown
        choices = []
        conditions_access_groups = build_filter_access_groups(self.request.user.profile.access_groups, True, '')
        for ef in ExecutionFlow.objects.filter(conditions_access_groups, ~Q(status='INVALID')).order_by('name'):
            choices.append((ef.id, ef.name))
            context['form'].fields['execution_flow'].choices = choices
        # setting the event source id and name to the dropdown
        choices = [(None, '---')]
        event_sources = self.filter_by_type(build_complemented_event_source_names(), [])
        for s in sorted(event_sources, key=lambda d: d['name']):
            choices.append((s['id'], s['name']))
        context['form'].fields['event_source'].choices = choices
        context['form_operation'] = 'update' if self.__class__.__name__ == 'ErrorDetectorUpdate' else 'create'
        distinct_event_source_type_ids = dict(map(lambda es: (es.id,
                                                              list(filter(None, set(self.get_est_id_from_children(es))))),
                                                  EventSource.objects.filter(status='VALID')))
        self.fill_empty_est_ids_from_parent(distinct_event_source_type_ids)
        context['event_source_to_event_source_type'] = json.dumps({k: self.get_est_list_by_es(v) for k, v in distinct_event_source_type_ids.items()})
        context['if_contains_reaction_worker'] = json.dumps(dict(map(lambda es: (es.id,
                                                                                 True if list(filter(None, self.is_worker_est_in_this_es_or_its_children(es))) else False),
                                                                     EventSource.objects.filter(status='VALID'))))
        return context

    def get_est_id_from_children(self, es):
        est = []
        for event_source in EventSource.objects.filter(Q(parent=es.id) & Q(status='VALID')):
            est.extend(self.get_est_id_from_children(event_source))
        est.append(self.get_est_id(es.event_source_type))
        return est

    def is_worker_est_in_this_es_or_its_children(self, es):
        est = []
        for event_source in EventSource.objects.filter(Q(parent=es.id) & Q(status='VALID')):
            est.extend(self.is_worker_est_in_this_es_or_its_children(event_source))
        if es.event_source_type and es.event_source_type.code == 'REACTION-WORKER':
            est.append(1)
        return est

    def get_est_id(self, est):
        return est.id if est else None

    def get_est_list_by_es(self, est_ids):
        est_list = list(EventSourceType.objects.filter(pk__in = est_ids))
        pti_ed_list = []
        for est in est_list:
            if est.path_to_identifiers:
                pti_list = json.loads(est.path_to_identifiers)
                for pti in pti_list:
                    if pti['output'] == 'ERROR_DETECTOR':
                        pti['event_source_type_name'] = est.name
                        pti_ed_list.append(pti)
        return pti_ed_list

    def fill_empty_est_ids_from_parent(self, est_ids):
        for k, v in est_ids.items():
            if not v:
                est_from_parent = self.get_est_from_parent(k)
                if est_from_parent:
                    est_ids[k] = [est_from_parent]

    def get_est_from_parent(self, es_id):
        es = EventSource.objects.get(id=es_id)
        if es.parent:
            if es.parent.event_source_type:
                return es.parent.event_source_type.pk
            else:
                return self.get_est_from_parent(es.parent.pk)
        else:
            return None

    # retrieves all the ITEM event sources and only those GROUP ones which (or one of its groups) have ITEM event source(s)
    def filter_by_type(self, event_sources, filtered_event_sources):
        for _es in event_sources[:]:
            for es in event_sources[:]:
                if es['type'] == 'ITEM':
                    filtered_event_sources.append(es)
                    event_sources.remove(es)
                else:
                    if len([filtered_es for filtered_es in filtered_event_sources if filtered_es['parent_id'] == es['id']]) > 0:
                        filtered_event_sources.append(es)
                        event_sources.remove(es)
        return filtered_event_sources


class ErrorDetectorUpdate(ErrorDetectorUpdateCreateView, UpdateView):
    pass


class ErrorDetectorCreate(ErrorDetectorUpdateCreateView, CreateView):
    pass

# -------------------------------------------------- for REST --------------------------------------------------

@login_required
@permission_required('auth.can_use_admin_errordetector', raise_exception=True)
def delete_errordetector(request, pk):
    logger.info('delete_errordetector is called - request={}; pk={}'.format(request,pk))
    try:
        ErrorDetector.objects.filter(id = pk).delete()
        return HttpResponseRedirect(reverse_lazy('admin_errordetector_list'))
    except IntegrityError:
        message = 'The error detector cannot be deleted as it is currently being used in somewhere else!'
        logger.exception(message)
        return render(request, 'business_error.html', {'message': message})


@login_required_for_rest
@permission_required('auth.can_use_admin_errordetector', raise_exception=True)
@api_view(['GET'])
@transaction.atomic
def get_event_source(request, pk):
    logger.info('Getting the event source. pk={}, request={}'.format(pk, request))

    event_source = get_object_or_404(EventSource, id=pk)
    serializer = EventSourceTypeSerializer(event_source, many=False)

    return Response(serializer.data, status=status.HTTP_200_OK)


@login_required_for_rest
@permission_required('auth.can_use_admin_errordetector', raise_exception=True)
@api_view(['GET'])
@transaction.atomic
def get_errordetector_endpoint(request, pk):
    logger.info('Getting the endpoint to be called from external monitoring app. pk={}, request={}'.format(pk, request))

    error_detector = get_object_or_404(ErrorDetector, id=pk)

    item_event_sources = []
    get_item_event_sources(error_detector.event_source, item_event_sources)

    fill_est_and_identifiers_in_item_event_sources(item_event_sources)

    result_list = []
    for item_event_source in item_event_sources:
        result = {'name': item_event_source.name,
                  'id': item_event_source.pk}
        if item_event_source.event_source_type.code == 'REACTION-WORKER':
            result['is_reaction_worker'] = True
        else:
            try:
                result.update(get_endpoint_to_be_called(error_detector, item_event_source))
            except KeyError:
                message = "The endpoint cannot be determined! Please check if all the identifier values are specified in the event source [{}] / error detector [{}].".format(item_event_source.name, error_detector.name)
                logger.exception(message)
                return Response(message, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        result_list.append(result)
    return Response(result_list, status=status.HTTP_200_OK)


@login_required
@permission_required('auth.can_use_admin_errordetector', raise_exception=True)
def remove_history(request, pk):
    error_detector = get_object_or_404(ErrorDetector, pk=pk)
    Event.objects.filter(error_detector=error_detector).delete()
    return HttpResponseRedirect(reverse_lazy('admin_errordetector_update', kwargs={'pk': pk}))


# -------------------------------------------------- utility functions ------------------------------------------------
# filling the event source type and identifiers from parent if necessary
def fill_est_and_identifiers_in_item_event_sources(item_event_sources):
    for item_event_source in item_event_sources:
        fill_from_parent(item_event_source, 'event_source_type')
        fill_from_parent(item_event_source, 'identifiers')


def fill_from_parent(item_event_source, attribute):
    if not getattr(item_event_source, attribute):
        parent_event_source = item_event_source

management_app/admin_errordetector/templates/admin_errordetector/form.html
{% extends "base.html" %}

{% block title %}{% if form_operation == "update" %}Edit an existing error detector{% else %}Create a new error detector{% endif %}{% endblock %}

{% block content %}

    {% load static %}

    <link rel="stylesheet" href="{% static 'switch.css' %}" />

    <script src="{% static 'js/building_identifiers.js' %}"></script>

    <script>
        var urlForRebuildIdentifiers = "{% url 'admin_errordetector_event_source' pk='43957793052297467' %}";
        var eventSourceToEventSourceType = JSON.parse("{{ event_source_to_event_source_type|default_if_none:"{}"|escapejs }}");
        var ifContainsReactionWorker = JSON.parse("{{ if_contains_reaction_worker|default_if_none:"{}"|escapejs }}");

        $(document).ready(function() {
            buildIdentifiers(JSON.parse("{{object.identifiers|default_if_none:"{}"|escapejs}}"), {{object.event_source.pk}});
        });

        function escapeMessagePattern() {
            var pattern = $("#id_message_pattern").val();
            $("#id_message_pattern").val( pattern.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&') );
            $("#b_escape").prop('disabled', true);
        }

        function loadIdentifierTable(identifiers, path_to_identifiers) {
            $("#div_identifiers").show();
            $("#table_identifiers").find("tr:gt(0)").remove();
            numRows = 1;
            for(let i=0; i<path_to_identifiers.length; i++) {
                addRowToIdentifiers(path_to_identifiers[i], identifiers, true);
            }
        }

        function rebuildIdentifiers() {
            let event_source_id = $("#id_event_source").val();
            buildIdentifiers({}, event_source_id);
        }

        function buildIdentifiers(identifiers, event_source_id) {
            $("#div_step_3").hide();
            $("[id^='identifiers_name_']").remove();
            $("[id^='identifiers_value_']").remove();
            $("#div_message_pattern").hide();
            $("#id_message_pattern").prop('required',false);
            if (ifContainsReactionWorker[event_source_id]) {
                $("#div_step_3").show();
                $("#div_message_pattern").show();
                $("#id_message_pattern").prop('required',true);
            }
            $("#div_identifiers").hide();
            if (eventSourceToEventSourceType[event_source_id] && eventSourceToEventSourceType[event_source_id].length) {
                $("#div_step_3").show();
                loadIdentifierTable(identifiers, eventSourceToEventSourceType[event_source_id]);
            }
        }

        function removeRelatedEvents() {
            if (confirm('!!!! WARNING !!!!\nAre you sure that you want to remove the full history (i.e. all the events) of this error detector?')) {
                $("#loadingDiv").show();
                link = '{% url 'admin_errordetector_remove_history' pk=object.id %}';
                window.location = link;
            }
        }
    </script>

    <div class="heading1">Error Detector administration - {% if form_operation == "update" %}Edit{% else %}Create{% endif %}</div>

    <div class="container" style="padding-top: 30px;">
		<form method="post" id="f_error_detector_update" onsubmit="return convertIdentifiersToJSON(document.forms.f_error_detector_update)">
			{% csrf_token %}
			{{ form.non_field_errors }}

            <div class="row" style="padding-bottom: 10px;">
                <div class="col-md-2">
                    <label for="{{ form.name.id_for_label }}" style="padding-top: 8px;">Name :</label> <span class="glyphicon glyphicon-asterisk"></span>
                </div>
                <div class="col-md-10">
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
            </div>

            <div class="row ed_step">
                <div class="col-md-1">
                    <div class="ed_step_text">Step</div>
                    <div class="ed_step_nr">1</div>
                </div>
                <div class="col-md-11">
                    <div class="ed_step_header">Please specify <b>WHERE</b> to investigate (select an event source to be observed)!</div>
                    <div class="row">
                        <div class="col-md-2">
                            <label for="{{ form.event_source.id_for_label }}" style="padding-top: 8px;">Event source:</label>
                            <span class="glyphicon glyphicon-asterisk"></span>
                            <span class="glyphicon glyphicon-exclamation-sign" data-toggle="tooltip" title="Those GROUP event sources that don't have at least one ITEM child event source will be ignored in this list!&#10;Only the valid event sources are used to populate this list."></span>
                        </div>
                        <div class="col-md-10">
                            {{ form.event_source }}
                            {{ form.event_source.errors }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row ed_step">
                <div class="col-md-1">
                    <div class="ed_step_text">Step</div>
                    <div class="ed_step_nr">2</div>
                </div>
                <div class="col-md-11">
                    <div class="ed_step_header">Please specify <b>HOW</b> to resolve the incident (select a flow that will remedy the problem)!</div>
                    <div class="row">
                        <div class="col-md-2">
                            <label for="{{ form.execution_flow.id_for_label }}" style="padding-top: 8px;">Execution flow:</label> <span class="glyphicon glyphicon-asterisk"></span>
                        </div>
                        <div class="col-md-10">
                            {{ form.execution_flow }}
                            {{ form.execution_flow.errors }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row ed_step" id="div_step_3">
                <div class="col-md-1">
                    <div class="ed_step_text">Step</div>
                    <div class="ed_step_nr">3</div>
                </div>
                <div class="col-md-11">
                    <div class="ed_step_header">Please specify <b>WHAT</b> to investigate (define a pattern that will be monitored by Reaction Worker and/or identifiers that can come from event source types (external monitoring application) )!
                    <span class="glyphicon glyphicon-exclamation-sign" data-toggle="tooltip" title="All the identifiers are enlisted here which belong to the selected event source or to one of its descendant! When the event message arrives then the corresponding event source is chosen and only that/those identifier(s) will be used."></span></div>
                    <div class="row">
                        <div class="row" id="div_identifiers">
                            <div class="col-md-12">
                                <label style="padding-top: 8px;">Identifiers</label>
                                <span class="glyphicon glyphicon-question-sign" title="The following identifiers come from event source type(s) which determine(s) what to observer in the incoming event message sent by 3rd part monitoring solution."></span>
                            </div>
                            <div class="col-md-12">
                                <table class="data_table" id="table_identifiers" style="margin-top: 10px; margin-bottom: 10px;">
                                    <tr>
                                        <th class="data_table_header">Name</th>
                                        <th class="data_table_header">Source</th>
                                        <th class="data_table_header">Value
                                            <span class="glyphicon glyphicon-asterisk"></span>
                                            <span class="glyphicon glyphicon-exclamation-sign" data-toggle="tooltip" title="Regular expression can be defined. Please be aware that the following characters have to be escaped (if they are not part of the regular expression)!&#10;. $ ^ { [ ( | ) * + ? \&#10;For example: 'filter :{}' -> 'filter :\{\},'"></span>
                                        </th>
                                        <th class="data_table_header">Event source type</th>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div id="div_message_pattern" style="padding-top: 7px">
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="{{ form.message_pattern.id_for_label }}" style="padding-top: 8px;">Message pattern</label>
                                    <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" title="The message pattern belongs to Reaction Worker event source type only.&#10;Regular expression can be defined. Please be aware that the following characters have to be escaped (if they are not part of the regular expression)!&#10;. $ ^ { [ ( | ) * + ? \&#10;For example: 'filter :{}' -> 'filter :\{\},'"></span>
                                    <span class="glyphicon glyphicon-asterisk">
                                </div>
                            </div>
                            <div class="row" style="padding-top: 7px">
                                <div class="col-md-10">
                                    {{ form.message_pattern }}
                                    {{ form.message_pattern.errors }}
                                </div>
                                <div class="col-md-2">
                                    <input type="button" id="b_escape" value="Escape the reserved characters" onclick="escapeMessagePattern()"
                                           class="btn btn-primary" style="padding-left: 12px;"
                                           title="Escaping the reserved characters in the message pattern textfield.&#10;All the reserved characters will be escaped even if they are part of a valid regular expression! I.e. [a-z]*  ->  \[a\-z\]\*"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <hr/>

            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.multiple_events_cnt.id_for_label }}" style="padding-top: 8px;">The number of events needed to start the flow:<span class="glyphicon glyphicon-question-sign" title="If more errors (i.e. NullPointerExceptions in the log file) are needed to start the execution flow then the number of the errors can be specified here. It can contain only positive integer higher than 1. If only one error can start the flow then please empty the text field."></span> </label>
                </div>
                <div class="col-md-2">
                    {{ form.multiple_events_cnt }}
                    {{ form.multiple_events_cnt.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.multiple_events_timefr.id_for_label }}" style="padding-top: 8px;">Timeframe while the events have to arrive (sec):<span class="glyphicon glyphicon-question-sign" title="If more errors (i.e. NullPointerExceptions in the log file) can start the execution flow then the time frame of the errors can be specified here (i.e. 3 NullPointerExceptions have to arrive in 10 minutes)."></span> </label>
                </div>
                <div class="col-md-2">
                    {{ form.multiple_events_timefr }}
                    {{ form.multiple_events_timefr.errors }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                        <label for="{{ form.activated.id_for_label }}">Activated :</label>
                        No
                        <label class="switch" style="margin-left: 9px; margin-right: 9px; position: relative; top: 15px;">
                            {{ form.activated }}
                            <div class="slider"></div>
                        </label>
                        Yes
                        {{ form.activated.errors }}
                    </div>
                <div class="col-md-4">
                        <label for="{{ form.confirmation_needed.id_for_label }}">Confirmation needed: <span class="glyphicon glyphicon-question-sign" title="The flow to be executed has to be approved manually first. It will be only applied for events initiated by the log file (i.e. if a flow is executed manually or by the scheduler then it doesn't have to be confirmed)."></span> </label>
                        No
                        <label class="switch" style="margin-left: 9px; margin-right: 9px; position: relative; top: 15px;">
                            {{ form.confirmation_needed }}
                            <div class="slider"></div>
                        </label>
                        Yes
                        {{ form.confirmation_needed.errors }}
                </div>
            </div>

            <br>
            <input type="submit" value="Save" class="btn btn-primary"/>
            <a href="{% url 'admin_errordetector_list' %}" class="btn btn-primary">Cancel</a>
            <a href="#" class="btn btn-danger pull-right" onclick="removeRelatedEvents()" title="All the events will be deleted that are connected to this error detector.">Remove all related events!</a>
		</form>
	</div>

{% endblock %}